### PR TITLE
Fixes angular2-modal/provides.js not found

### PR DESCRIPTION
**Pull request by troyanskiy**
I had an issue working with angular2-seed.
It fixes  angular2-modal/provides.js not found.
Could you please merge and bump a new version please.
Thank you.

### CODE REVIEW

**Comment by shlomiassaf** [comment]
@troyanskiy Thank you!

Importing `index.js` from a directory means that the bundler/module loader doesn't handle a "main".

Did you try setting `'components/angular2-modal/providers': {main: 'index.js', defaultExtension: 'js'},`  in the package section within `systemjs.config.js`  ?

**Comment by troyanskiy** [comment]
@shlomiassaf I have tried many things, but I did not tries exactly that.
Any way I think it's better to have something, what does not need to many "movements" to initialise the module.
What do you think?

**Comment by shlomiassaf** [comment]
@troyanskiy I think it was fixed in version 2, right?

**Comment by troyanskiy** [comment]
I will test version 2

**Comment by troyanskiy** [comment]
@shlomiassaf Looks fine with ver 2. Thanks

**Pull request closed without merging**
