### PR TITLE
Don't force use of modal-size

### LINKED ISSUE #74: Don't force use of bootstrap modal sizes sm or lg
Bootstrap docs:
> Modals have two optional sizes, available via modifier classes to be placed on a .modal-dialog.

I think the default size for modals should be none and then you can add your `sm` or `lg` if you need a different sized modal.

### PR DESCRIPTION
**Pull request by ellern**
This fixes #74

### CODE REVIEW

**Comment by shlomiassaf** [comment]
I understand the need but it also error prone...

you can always do:
```ts
modal
  .title('custom size`)
  .size('custom' as any)
  .open();
```

or I can add a `customSize` setter...

The thing is, next version will be vendor specific and I want to follow the vendor implementation, user's can extend the lib but to have common ground I want to stay in par with the origin.

**Comment by ellern** [comment]
Why not just default to the same as bootstrap, eg. no size, and then use the size() to actually add the optional sm or lg size?

**Comment by shlomiassaf** [comment]
@ellern ok.

Can you post a PR that just remove the defaults?

btw, it's doable now by giving a default modal config with no dialog...

**Comment by ellern** [comment]
That's pretty much what the PR does now, except that it also fixes a small bug forcing you to put in either sm / lg in the `dialogClass` which effectively removes the possibility to add a custom class to the dialog (I know it can be "hacked" with :any)

**Comment by shlomiassaf** [comment]
Hi, Releases version 1.0
Implemented your suggestion, default is an empty string.

**Pull request closed without merging**
