### PR TITLE
Handle angular-universal's document is not defined exception

### PR DESCRIPTION
**Pull request by carathorys**
You can't use `document` in angular-universal, it triggers an `document is not defined` exception, but we can still detect if there is no document with an easy try-catch. 
With this modification, the modal basically works with angular-universal :)

### CODE REVIEW

**Comment by shlomiassaf** [comment]
Hi @carathorys 
Thank you for the contribution! much appreciated.

Can you update the PR to reflect the latest changes (support for RC5)
Basically the file has moved to `providers` directory....

**Comment by shlomiassaf** [comment]
Thanks!
Sorry for the trouble, but the commit log is quite noisy, can you squash? if not i'll do it... just let me know.

**Comment by inzerceubytovani** [comment]
Some progress here?

**Comment by davidthor** [comment]
Request here seemed stale - created a new PR solving the same problem.
https://github.com/shlomiassaf/angular2-modal/pull/311

**Comment by shlomiassaf** [comment]
Thank you for your contribution.

Due to a huge refactor I could not use the commit but I believe the issue is now fixed with version 3.0.0

If not, please feel free to open a new issue.

Version 3 comes with a better build (FESM) and the following changes:
```
* handle document for angular universal 
* refactor: use ng-template instead of template
* refactor: remove defaultOverlayTarget directive
* refactor: replace custom swpCmp with ngComponentOutlet

### BREAKING CHANGES

  - Moving to use <ng-template> will break applications running on < 4
  - Applications using defaultOverlayTarget (all of them) will have to omit it

```

([2f98e75](https://github.com/shlomiassaf/angular2-modal/commit/2f98e75))

**Pull request closed without merging**
