### PR TITLE
Fix AOT compilation error with angular-cli 1.0.0

### PR DESCRIPTION
**Pull request by achimha**

### CODE REVIEW

**Comment by josephtaylor** [comment]
Just curious, is there any chance of good fixes like this getting merged in this project? Noticed there's been no commits since January.

**Comment by shlomiassaf** [comment]
Didn't have the time lately

I will try to get to it this week.

I'll focus on urgent, blocking issues.

Most feature requests can be implemented by implementing a plugin...

**Comment by josephtaylor** [comment]
thanks for the info ! really glad to know it's still active.

**Comment by shlomiassaf** [comment]
Thank you for your contribution.

Due to a huge refactor I could not use the commit but I believe the issue is now fixed with version 3.0.0

If not, please feel free to open a new issue.

Version 3 comes with a better build (FESM) and the following changes:
```
* handle document for angular universal 
* refactor: use ng-template instead of template
* refactor: remove defaultOverlayTarget directive
* refactor: replace custom swpCmp with ngComponentOutlet

### BREAKING CHANGES

  - Moving to use <ng-template> will break applications running on < 4
  - Applications using defaultOverlayTarget (all of them) will have to omit it

```

([2f98e75](https://github.com/shlomiassaf/angular2-modal/commit/2f98e75))

**Pull request closed without merging**
