### PR TITLE
Added input field in bootstrap prompt

### PR DESCRIPTION
**Pull request by CaselIT**
This PR adds the input field in the bootstrap prompt as mentioned in #119

### CODE REVIEW

**Comment by shlomiassaf** [comment]
@CaselIT can you rebase and refactor for beta 2?

Also, please squash the commits and use angular style commit messages for the change log.

Thanks!

**Comment by CaselIT** [comment]
I'll look into it.

Do you have a reference for the the commit style you would prefer?
Thanks

**Comment by CaselIT** [comment]
I've updated it.
Please note that I've tested it on the beta 10, but could not check if it still works in the beta 11 since I encounter #174

**Comment by shlomiassaf** [comment]
@CaselIT Thanks.

One issue, you make use for `FormsModule` for `NgModel` support, however I would like to avoid it since one might not use forms at all or one might use REACTIVE forms... It will force importing that module for this simple input.

In VEX I did it without NgModel, can you take a look and say what you think?

**Comment by CaselIT** [comment]
I've seen that in vex you use `(change)`.
I'm not sure if in the vex version you can set the initial value this way.
I wanted to provide this functionality.
In any case I've used the form since it was already a dependency of the project. But if it is not used anywhere else I agree that it's better to remove it.
I'll update the PR later

**Comment by CaselIT** [comment]
@shlomiassaf I've removed the form dependency while retained the initial value function by using `@ViewChild`. 
I do not think the vex plugin had this function. I could add it if you like.

**Comment by shlomiassaf** [comment]
@CaselIT Thanks!

There's no need for `@ViewChild`, a simple `[value]="defaultValue"` is enough.

I refactored it, will post with RC6 update.

**Comment by CaselIT** [comment]
Did not know/forgot about that!

Thanks

**Pull request merged**
